### ISSUE TITLE
Map icons aren't loading correctly

### ISSUE THREAD

**Issue by jrdh** [NaturalHistoryMuseum/versioned-datastore-tile-server#12]
We have some missing images on our map!

![image](https://user-images.githubusercontent.com/4718259/195401904-c13e0338-e671-44ff-a893-b8f3c69ae4e7.png)

The images are:
- https://data.nhm.ac.uk/webassets/ckanext-versioned-tiledmap/images/spritesheet-2x.png
- https://data.nhm.ac.uk/webassets/ckanext-versioned-tiledmap/images/toggle.png

**Comment by alycejenni** [comment]
Temporarily fixed by copying the images folder over to the webassets folder manually
